version: "3"

networks:
  loki:

services:
  app:
    image: node
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: node app.js

  loki:
    image: grafana/loki:2.3.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.3.0
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki
    volumes:
      - ./promtail.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
    volumes:
      - ./loki-source.yml:/etc/grafana/provisioning/datasources/loki-source.yml
